package IndiaAlleleFinder::Model::IndiaAlleleFinderDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'IndiaAlleleFinder::Schema::IndiaAlleleFinderDB',
    
    connect_info => {
        dsn => 'dbi:mysql:IndiaAlleleFinderDB',
        user => 'root',
        password => 'useyourownpassword!',
        quote_names => q{1},
    }
);

=head1 NAME

IndiaAlleleFinder::Model::IndiaAlleleFinderDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<IndiaAlleleFinder>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<IndiaAlleleFinder::Schema::IndiaAlleleFinderDB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

Jimmy Zhang

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
